name: habbit_tracker
description: "This application can track your daily activity. If you want to change your habbit, it might help."
  
  
publish_to: 'none'   

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

   
dependencies:
  flutter:
    sdk: flutter
  adaptive_action_sheet: 2.0.3
  cupertino_icons: 1.0.8
  flutter_launcher_icons: 0.13.1
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10
  hive: 2.2.3
  hive_flutter: 1.1.0
  modal_bottom_sheet: 3.0.0
  page_flip_builder: 0.1.4
  uuid: 4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.11

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon.png"
    
         
  flutter_lints: ^3.0.0

   
flutter:
  uses-material-design: true

  assets:
   - assets/

    
    
    
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
